### ISSUE TITLE
Possible update idea on your article about multi-tier-loadbalancer (lab-3tier-lb) ?!

### ISSUE THREAD

**Issue by mcarbonneaux** [vincentbernat/network-lab#8]
Hi, your article are very interesting, he had inspiring me about. 
https://vincent.bernat.ch/fr/blog/2018-repartiteur-charge-multi-niveaux 

I've tryed differente solution about what you explain, ipvs, katran, github lb director, google seesaw, keepalived, and ....
i've tested cilium overley with k8s that implemente L4 load balacing DSR with maglev with eBPF/XDP and BGP Load balancing in one solution. 

His make possible to implemente what you explain in your article, with K8S simple object with kubectl apply (support Load Balancer service type).

They use of k8s make possible to implemente the LB L7 in distributed maner (haproxy, nginx, envoy or what you whant as pod)...
and make possible to scale also on BGP and L4 level dynamicly... you add kubernetes nodes and L4/BGP grow... you add node and L7 can grow...

All are industrialized thanks to kubernetes (dynamic cluster grow at each level). 

Plus cilium not use full ip (like GRE/GUE/Foo-Over-UDP/Geneve, etc...) encapsulation between L4 and L7, they use simple SNAT/DNAT in setting the destination IP (VIP) in TCP options field... in distributed way without storing state anywhere... this field are used to DNAT in output of the L4 to the real ip of the L7 pod, and SNAT in the output of the pod to respond directly to the client... all are done with eBPF by cilium...

- https://docs.cilium.io/en/v1.9/gettingstarted/kubeproxy-free/#direct-server-return-dsr
- https://docs.cilium.io/en/v1.10/gettingstarted/bgp/
- https://cilium.io/blog/2020/06/22/cilium-18 
- https://cilium.io/blog/2021/05/20/cilium-110

You can also use kube router + metallb to do the same but not with the same performence (kube router use ipvs for LB L4 DSR in place of eBPF/XDP), and with ip encapsulation...
- https://www.kube-router.io/docs/user-guide/#direct-server-return
- https://github.com/cloudnativelabs/kube-router/blob/master/docs/bgp.md
- https://metallb.universe.tf/

And linux IPVS support DSR with maglev algorithme since [linux kernel 4.18](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=039f32e8cdea29b4d0680df7a83817b5ec4166e1).

I think that while be interesting to update your article with this solutions  !?

I've made a test bed with vagrant on my github : 
https://github.com/mcarbonneaux/vagrant-kubeadm-cluster-mca

**Comment by vincentbernat** [comment]
Thanks for the pointers. Feel free to post them as a comment on the blog. I can't really expand an existing article as much as you do, but I have added a small paragraph about Cilium.

**Comment by mcarbonneaux** [comment]
lool ! i've not seen that i can comment on your blog !
